### ISSUE TITLE
Empty results when columns is greater than 26

### ISSUE THREAD

**Issue by bobandjokic** [SC5/google-sheets-translate#2]
When worksheet have more than 26 columns (continued with AA, AB...), getTranslations() returns empty object. Everything works fine when columns are A-Z. Is there a way to fix this?

Thanks!

**Comment by juhamust** [comment]
Thanks for finding the root cause and fixing the issue: https://github.com/SC5/google-sheets-api/pull/7
This module also now requires the latest version of google-sheets-api, hence fixing the specified issue.
